### PR TITLE
Add automatic builds

### LINKED ISSUE #43: Automatic build of executables upon release?
I noticed that some repos have automatically built binaries upon release. In our case I guess this would be the `rinex-cli`, `crx2rnx`, and `rnx2crx` binaries.

[This Github Action](https://github.com/marketplace/actions/rust-release-binary#build-windows-linux-and-mac-with-native-zip-types) might be able to do this. People can then check out the executables without having to install the full Rust toolset.

### PR DESCRIPTION
**Pull request by larsnaesbye**
Make and add Windows and Mac Intel binaries when releasing
 
 Fixes #43

### CODE REVIEW

**Comment by larsnaesbye** [comment]
I had to temporarily give up Linux and macOS ARM builds, but this will be fixed fairly soon I hope.

**Comment by gwbres** [comment]
Hello @larsnaesbye,
sorry I did not get a chance to look at this but I'll spend sometime on it tonight.
We'll have this feature for the next release

**Comment by larsnaesbye** [comment]
I am not so worried about prebuilt Linux binaries. Linux folks know how to build.
As for the macOS ARM native versions - the best thing is to fix it upstream in the Build Action: https://github.com/rust-build/rust-build.action/issues/4

**Review by gwbres — APPROVED** [review]

**Comment by larsnaesbye** [comment]
@gwbres did you manage to get Linux build to work? I can't make it work with the same settings in my own repo - I get an error saying it's not supported and I should use linux-musl instead.

**Comment by gwbres** [comment]
> @gwbres did you manage to get Linux build to work? I can't make it work with the same settings in my own repo - I get an error saying it's not supported and I should use linux-musl instead.

Hello  @larsnaesbye,
I did not get a change to try it, as it only builds when a tag is released.
I naively took it from the official list. Can you show me an error log?

PS: V8.0.0 is stuck until the `Hifitime` topic is completely merged

**Comment by larsnaesbye** [comment]
This is the guide I was using:

https://github.com/rust-build/rust-build.action#build-windows-linux-and-mac-with-native-zip-types

**Pull request merged**
