### PR TITLE
Add NAV and OBS testdata from same epoch

### PR DESCRIPTION
**Pull request by larsnaesbye**

### CODE REVIEW

**Comment by larsnaesbye** [comment]
Apparently one file fails on gzip? I have no problem unpacking it locally in both Linux and Windows...

**Review by gwbres — APPROVED** [review]

**Comment by gwbres** [comment]
> Apparently one file fails on gzip? I have no problem unpacking it locally in both Linux and Windows...

Apparently it's complaining about the `gzip` header content, for both new Observation files. Indeed `gzip -d` also worked on my side.

**Comment by gwbres** [comment]
I'm not worried about this error, we'll figure it out.
I dropped a message on the decompression library this crate is currently using. I just demonstrated the two files are clearly gzip compressed and not anything else.

Thank you for the data, I will work on the double diff operation in the next few days

**Comment by larsnaesbye** [comment]
Maybe this thread can help? 
https://users.rust-lang.org/t/flate2-decompress-is-returning-an-empty-slice/81931/8

My good colleague @busstoptaktik pointed me in the direction of it.

**Pull request merged**
