### PR TITLE
Update strum dependencies to latest

### PR DESCRIPTION
**Pull request by larsnaesbye**

### CODE REVIEW

**Comment by larsnaesbye** [comment]
Okay, this one did not fail in my IDE (IntelliJ with Rust plugin). But that may be because not all tests were run...(?)

**Comment by larsnaesbye** [comment]
Giving this up for now.

**Comment by gwbres** [comment]
Hello @larsnaesbye 
I did not have time to give this one a chance, but it looks like there's a combination of problems between
* clap latest features or how to deal with them
* and how we test a command line application in the CI

it's not that big of a deal, you can leave it open, I'll inquire it

**Comment by larsnaesbye** [comment]
Yes, the breaking changes in clap 3 were bigger than I thought. I think this is a lower priority, however.

**Pull request closed without merging**
