### PR TITLE
First rustfmt config

### PR DESCRIPTION
**Pull request by larsnaesbye**
Starting a configuration file for `rustfmt`.

Finetuning comes later.

### CODE REVIEW

**Comment by gwbres** [comment]
Hello Lars,

[closely related to this topic](https://github.com/gwbres/rinex/issues/59)

`cargo fmt --all -- --check`  takes advantage for the rustfmt config file you provided, and checks for the coding style automatically.
That means the CI willf ail on contributions that did not wrapped a `cargo fmt`.
 
Obviously this is expected to fail until we execute a `cargo fmt` ourselves, into the repository.
I'm OK if we do that with this PR so we set up everything correctly

We also take advantage of the basic Rust github action (`action-rs`) which helps setup the Rust environment, and simplifies things a little bit

**Comment by larsnaesbye** [comment]
I guess it's fine to require that `cargo fmt` is run before pushing. After all, our CI will tell us if it's formatted properly before a merge.

**Comment by gwbres** [comment]
> I guess it's fine to require that `cargo fmt` is run before pushing. After all, our CI will tell us if it's formatted properly before a merge.

Yes, any PR that do not respect the rules get blocked until the CI is resolved (`pull_request: "main"` trigger).

Are you OK with pushing a `cargo fmt` into the repo ?

**Comment by larsnaesbye** [comment]
Sure, it makes perfect sense to do it. I might forget it the first time though :-D

**Comment by larsnaesbye** [comment]
@gwbres since we are now requiring users to do something (formatting) before submitting, I added a preliminary `CONTRIBUTING.md` file. With time it could grow into something bigger, like described in https://mozillascience.github.io/working-open-workshop/contributing/ .

**Comment by gwbres** [comment]
I'll rebase the branch after lunch 🍕

**Comment by larsnaesbye** [comment]
> I'll rebase the branch after lunch 🍕

Bon appetit!

**Review by gwbres — APPROVED** [review]

**Pull request merged**
